pool: Nitin-ADOpipeline

trigger:
- main
- feature/*

stages:
- stage: stage_tf_validate
  displayName: stage_tf_validate
  jobs:
  - job: job_tf_validate
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: '-reconfigure'
        workingDirectory: '$(System.DefaultWorkingDirectory)/rootmodule/env/preprod'
        backendServiceArm: 'nitin-SC'
        backendAzureRmStorageAccountName: 'strgbackend11111'
        backendAzureRmContainerName: 'tfstate-preprod'
        backendAzureRmKey: 'preprod.terraform.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/rootmodule/env/preprod'

- stage: stage_tf_plan
  displayName: stage_tf_plan
  condition: succeeded()
  dependsOn: stage_tf_validate
  jobs:
  - job: job_tf_plan
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: '-reconfigure'
        workingDirectory: '$(System.DefaultWorkingDirectory)/rootmodule/env/preprod'
        backendServiceArm: 'nitin-SC'
        backendAzureRmStorageAccountName: 'strgbackend11111'
        backendAzureRmContainerName: 'tfstate-preprod'
        backendAzureRmKey: 'preprod.terraform.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/rootmodule/env/preprod'
        environmentServiceNameAzureRM: 'nitin-SC'

# - stage: stage_tf_scan
#   displayName: stage_tf_scan
#   jobs:
#   - job: job_tf_scan
#     steps:
#     - task: PowerShell@2
#       inputs:
#         targetType: 'inline'
#         script: 'Write-Host "Hello World"'

- stage: stage_tf_apply
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))  # Apply ONLY when pipeline is running from main branch
  dependsOn: stage_tf_plan
  displayName: stage_tf_apply
  jobs:
    # Manual Approval
  - job: manual_approval
    displayName: 'Manual Approval Before Apply'
    pool: server

    steps:
    - task: ManualValidation@0
      displayName: 'Approve Terraform Apply'
      timeoutInMinutes: 1440
      inputs:
        notifyUsers: '' # nitin@example.com
        instructions: |
          Please review the Terraform plan.
          Approve this step to continue with Terraform Apply.
        onTimeout: 'reject'

  - job: job_tf_apply
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: '-reconfigure'
        workingDirectory: '$(System.DefaultWorkingDirectory)/rootmodule/env/preprod'
        backendServiceArm: 'nitin-SC'
        backendAzureRmStorageAccountName: 'strgbackend11111'
        backendAzureRmContainerName: 'tfstate-preprod'
        backendAzureRmKey: 'preprod.terraform.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/rootmodule/env/preprod'
        environmentServiceNameAzureRM: 'nitin-SC'
    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)/rootmodule/env/preprod'
        environmentServiceNameAzureRM: 'nitin-SC'